<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Deskhand.Http</RootNamespace>
    <AssemblyName>deskhand-http</AssemblyName>
    <Platforms>x64</Platforms>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Deskhand.Core\Deskhand.Core.csproj" />
  </ItemGroup>

</Project>
